server {
    listen 80;
    server_name _;

    location = / {
        return 301 /SIGEI/;
    }

    location /SIGEI/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ /SIGEI/index.html;
    }
}