export const ENDPOINTS = {
     AUTH: {
          LOGIN: "/api/auth/login",
          REFRESH: "/api/auth/refresh",
          LOGOUT: "/api/auth/logout",
     },
     USERS: {
          BASE: "/api/users",
          BY_ID: (id) => `/api/users/${id}`,
          ME: "/api/users/me",
          BY_STATUS: (status) => `/api/users/status/${status}`,
          BY_ROLE_STATUS: (role, status) => `/api/users/role/${role}/status/${status}`,
          BY_INSTITUTION: (institutionId) => `/api/users/institution/${institutionId}`,
          RESTORE: (id) => `/api/users/${id}/restore`,
     },
     TEACHER_ASSIGNMENTS: {
          BASE: "/api/teacher-assignments",
          BY_ID: (id) => `/api/teacher-assignments/${id}`,
          BY_TEACHER: (teacherUserId) => `/api/teacher-assignments/teacher/${teacherUserId}`,
          BY_INSTITUTION: (institutionId) => `/api/teacher-assignments/institution/${institutionId}`,
          BY_ACADEMIC_YEAR: (year) => `/api/teacher-assignments/academic-year/${year}`,
          BY_STATUS: (status) => `/api/teacher-assignments/status/${status}`,
          BY_TYPE: (type) => `/api/teacher-assignments/type/${type}`,
          RESTORE: (id) => `/api/teacher-assignments/${id}/restore`,
     },
     ASSIGNMENTS_MANAGEMENT: {
          BASE: "/api/assignments-management",
          CLASSROOMS: (assignmentId) => `/api/assignments-management/${assignmentId}/classrooms`,
          CLASSROOM_BY_ID: (assignmentId, classroomId) =>
               `/api/assignments-management/${assignmentId}/classrooms/${classroomId}`,
          SCHEDULES: (assignmentId) => `/api/assignments-management/${assignmentId}/schedules`,
          SCHEDULE_BY_ID: (assignmentId, scheduleId) =>
               `/api/assignments-management/${assignmentId}/schedules/${scheduleId}`,
     },
     INSTITUTIONS: {
          BASE: "/api/institutions",
          BY_ID: (id) => `/api/institutions/${id}`,
          DETAIL: (id) => `/api/institutions/${id}/detail`,
          RESTORE: (id) => `/api/institutions/${id}/restore`,
     },
     CLASSROOMS: {
          BASE: "/api/classrooms",
          BY_ID: (id) => `/api/classrooms/${id}`,
          BY_INSTITUTION: (institutionId) => `/api/classrooms/institution/${institutionId}`,
          RESTORE: (id) => `/api/classrooms/${id}/restore`,
     },
     STUDENTS: {
          BASE: "/api/students",
          BY_ID: (id) => `/api/students/${id}`,
          BY_STATUS: (status) => `/api/students/status/${status}`,
          BY_CUI: (cui) => `/api/students/cui/${cui}`,
          BY_CLASSROOM: (classroomId) => `/api/students/classroom/${classroomId}`,
          BY_INSTITUTION: (institutionId) => `/api/students/institution/${institutionId}`,
          MY_CHILDREN: (documentNumber) => `/api/students/my-children/${documentNumber}`,
          RESTORE: (id) => `/api/students/${id}/restore`,
          EXISTS_CUI: (cui) => `/api/students/exists/cui/${cui}`,
          EXISTS_DOCUMENT: (doc) => `/api/students/exists/document/${doc}`,
     },
     GUARDIANS: {
          BASE: "/api/guardians",
          BY_ID: (id) => `/api/guardians/${id}`,
          BY_STUDENT: (studentId) => `/api/guardians/student/${studentId}`,
          EXISTS_DOCUMENT: (doc) => `/api/guardians/exists/document/${doc}`,
          EXISTS_PHONE: (phone) => `/api/guardians/exists/phone/${phone}`,
          EXISTS_EMAIL: (email) => `/api/guardians/exists/email/${email}`,
          EXISTS_WHATSAPP: (whatsapp) => `/api/guardians/exists/whatsapp/${whatsapp}`,
     },
     ENROLLMENTS: {
          BASE: "/api/v1/enrollments",
          BY_ID: (id) => `/api/v1/enrollments/${id}`,
          BY_STUDENT: (studentId) => `/api/v1/enrollments/student/${studentId}`,
          BY_PERIOD: (periodId) => `/api/v1/enrollments/period/${periodId}`,
          BY_INSTITUTION: (institutionId) => `/api/v1/enrollments/institution/${institutionId}`,
          RESTORE: (id) => `/api/v1/enrollments/${id}/restore`,
          ACTIVATE: (id) => `/api/v1/enrollments/${id}/activate`,
          SET_PENDING: (id) => `/api/v1/enrollments/${id}/set-pending`,
     },
     ACADEMIC_PERIODS: {
          BASE: "/api/v1/academic-periods",
          BY_ID: (id) => `/api/v1/academic-periods/${id}`,
          BY_INSTITUTION: (institutionId) => `/api/v1/academic-periods/institution/${institutionId}`,
          BY_STATUS: (status) => `/api/v1/academic-periods/status/${status}`,
          ACTIVE: "/api/v1/academic-periods/active",
          ACTIVATE: (id) => `/api/v1/academic-periods/${id}/activate`,
          CLOSE: (id) => `/api/v1/academic-periods/${id}/close`,
     },
     ACADEMIC: {
          COURSES: {
               BASE: "/api/v1/courses",
               BY_ID: (id) => `/api/v1/courses/${id}`,
               BY_INSTITUTION: (institutionId) => `/api/v1/courses/institution/${institutionId}`,
               ACTIVE_BY_INSTITUTION: (institutionId) => `/api/v1/courses/institution/${institutionId}/active`,
               RESTORE: (id) => `/api/v1/courses/${id}/restore`,
          },
          COMPETENCIES: {
               BASE: "/api/v1/competencies",
               BY_ID: (id) => `/api/v1/competencies/${id}`,
               BY_COURSE: (courseId) => `/api/v1/competencies/course/${courseId}`,
               ACTIVE_BY_COURSE: (courseId) => `/api/v1/competencies/course/${courseId}/active`,
               RESTORE: (id) => `/api/v1/competencies/${id}/restore`,
          },
          CAPACITIES: {
               BASE: "/api/v1/capacities",
               BY_ID: (id) => `/api/v1/capacities/${id}`,
               BY_COMPETENCY: (competencyId) => `/api/v1/capacities/competency/${competencyId}`,
               ACTIVE_BY_COMPETENCY: (competencyId) => `/api/v1/capacities/competency/${competencyId}/active`,
               RESTORE: (id) => `/api/v1/capacities/${id}/restore`,
          },
          PERFORMANCES: {
               BASE: "/api/v1/performances",
               BY_ID: (id) => `/api/v1/performances/${id}`,
               BY_CAPACITY: (capacityId) => `/api/v1/performances/capacity/${capacityId}`,
               ACTIVE_BY_CAPACITY: (capacityId) => `/api/v1/performances/capacity/${capacityId}/active`,
               RESTORE: (id) => `/api/v1/performances/${id}/restore`,
          },
     },
     GRADES: {
          BASE: "/api/grades",
          BY_STUDENT: (studentId) => `/api/grades/student/${studentId}`,
     },
     REPORT_CARDS: {
          BASE: "/api/v1/reportcards",
          BY_ID: (id) => `/api/v1/reportcards/${id}`,
          BY_STUDENT: (studentId) => `/api/v1/reportcards/student/${studentId}`,
          BY_CLASSROOM: (classroomId) => `/api/v1/reportcards/classroom/${classroomId}`,
          BY_INSTITUTION: (institutionId) => `/api/v1/reportcards/institution/${institutionId}`,
          BY_STATUS: (status) => `/api/v1/reportcards/status/${status}`,
          MY_REPORTCARDS: "/api/v1/reportcards/my-reportcards",
          MY_INSTITUTION: "/api/v1/reportcards/my-institution",
          RESTORE: (id) => `/api/v1/reportcards/${id}/restore`,
     },
     ATTENDANCE: {
          BASE: "/api/attendance",
          BY_ID: (id) => `/api/attendance/${id}`,
          BY_STUDENT: (studentId) => `/api/attendance/student/${studentId}`,
          BY_CLASSROOM: (classroomId) => `/api/attendance/classroom/${classroomId}`,
          BY_DATE: (date) => `/api/attendance/date/${date}`,
          BULK: "/api/attendance/bulk",
          JUSTIFY: (id) => `/api/attendance/${id}/justify`,
          PICKUP: (id) => `/api/attendance/${id}/pickup`,
     },
     DISCIPLINE: {
          INCIDENTS: {
               BASE: "/api/v1/incidents",
               BY_ID: (id) => `/api/v1/incidents/${id}`,
               BY_STUDENT: (studentId) => `/api/v1/incidents/student/${studentId}`,
               BY_STATUS: (status) => `/api/v1/incidents/status/${status}`,
               RESOLVE: (id) => `/api/v1/incidents/${id}/resolve`,
               CHANGE_STATUS: (id) => `/api/v1/incidents/${id}/status`,
          },
     },
     EVALUATIONS: {
          BASE: "/api/evaluations",
          BY_ID: (id) => `/api/evaluations/${id}`,
          DETAILS: (id) => `/api/evaluations/${id}/details`,
          BY_TEACHER_CLASSROOM: (teacherId, classroomId) => `/api/evaluations/teacher/${teacherId}/classroom/${classroomId}`,
          COURSES_BY_TEACHER_CLASSROOM: (teacherId, classroomId) => `/api/evaluations/teacher/${teacherId}/classroom/${classroomId}/courses`,
          COMPETENCIES_BY_TEACHER_COURSE: (teacherId, courseId) => `/api/evaluations/teacher/${teacherId}/course/${courseId}/competencies`,
          UPDATE_DETAIL: "/api/evaluations/detail",
          FINALIZE: (id) => `/api/evaluations/${id}/finalize`,
     },
     PSYCHOLOGY: {
          EVALUATIONS: {
               BASE: "/api/psychological-evaluations",
               BY_ID: (id) => `/api/psychological-evaluations/${id}`,
               BY_STUDENT: (studentId) => `/api/psychological-evaluations/student/${studentId}`,
               BY_INSTITUTION: (institutionId) => `/api/psychological-evaluations/institution/${institutionId}`,
               BY_CLASSROOM: (classroomId) => `/api/psychological-evaluations/classroom/${classroomId}`,
               RESTORE: (id) => `/api/psychological-evaluations/${id}/restore`,
               HARD_DELETE: (id) => `/api/psychological-evaluations/${id}/hard`,
               START_SCHEDULED: (id) => `/api/psychological-evaluations/${id}/start`,
          },
     },
     EVENTS: {
          BASE: "/api/v1/events",
          BY_ID: (id) => `/api/v1/events/${id}`,
          BY_INSTITUTION: (institutionId) => `/api/v1/events/institution/${institutionId}`,
          INACTIVE: "/api/v1/events/inactive",
          RESTORE: (id) => `/api/v1/events/${id}/restore`,
     },
     CALENDARS: {
          BASE: "/api/v1/calendars",
          BY_ID: (id) => `/api/v1/calendars/${id}`,
          BY_INSTITUTION: (institutionId) => `/api/v1/calendars/institution/${institutionId}`,
          WITH_EVENTS: (id) => `/api/v1/calendars/${id}/events`,
          IMPORT: "/api/v1/calendars/import",
          ADD_EVENTS: (id) => `/api/v1/calendars/${id}/events`,
     },
     CIVIC_DATES: {
          BASE: "/api/civic-dates",
          BY_ID: (id) => `/api/civic-dates/${id}`,
          BY_YEAR: (year) => `/api/civic-dates/year/${year}`,
          BY_MONTH: (year, month) => `/api/civic-dates/year/${year}/month/${month}`,
          BY_DATE_RANGE: (startDate, endDate) => `/api/civic-dates/range?startDate=${startDate}&endDate=${endDate}`,
          HOLIDAYS: (year) => `/api/civic-dates/year/${year}/holidays`,
     },
};
